export default [
  {
    id: 1,
    chatfrom: 1,
    chatto: 2,
    data: [{ key: "value" }, { key: "value" }, { key: "value" }],
    lastMessage: "this is the last",
    avatar: "",
    title: "fake user",
    ispin: false,
    lastSeen: "4:53pm",
  },
  {
    id: 2,
    chatfrom: 1,
    chatto: 2,
    data: [{ key: "value" }, { key: "value" }, { key: "value" }],
    lastMessage: "this is the last",
    avatar: "",
    title: "fake user",
    ispin: false,
    lastSeen: "4:53pm",
  },
  {
    id: 3,
    chatfrom: 1,
    chatto: 2,
    data: [{ key: "value" }, { key: "value" }, { key: "value" }],
    lastMessage: "this is the last",
    avatar: "",
    title: "fake user",
    ispin: false,
    lastSeen: "4:53pm",
  },
  {
    id: 4,
    chatfrom: 1,
    chatto: 2,
    data: [{ key: "value" }, { key: "value" }, { key: "value" }],
    lastMessage: "this is the last",
    avatar: "",
    title: "fake user",
    ispin: false,
    lastSeen: "4:53pm",
  },
  {
    id: 5,
    chatfrom: 1,
    chatto: 2,
    data: [{ key: "value" }, { key: "value" }, { key: "value" }],
    lastMessage: "this is the last",
    avatar: "",
    title: "fake user",
    ispin: false,
    lastSeen: "4:53pm",
  },
  {
    id: 6,
    chatfrom: 1,
    chatto: 2,
    data: [{ key: "value" }, { key: "value" }, { key: "value" }],
    lastMessage: "this is the last",
    avatar: "",
    title: "fake user",
    ispin: false,
    lastSeen: "4:53pm",
  },
  {
    id: 7,
    chatfrom: 1,
    chatto: 2,
    data: [{ key: "value" }, { key: "value" }, { key: "value" }],
    lastMessage: "this is the last",
    avatar: "",
    title: "fake user",
    ispin: false,
    lastSeen: "4:53pm",
  },
  {
    id: 8,
    chatfrom: 1,
    chatto: 2,
    data: [{ key: "value" }, { key: "value" }, { key: "value" }],
    lastMessage: "this is the last",
    avatar: "",
    title: "fake user",
    ispin: false,
    lastSeen: "4:53pm",
  },
];
